<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-JO_BlazorDemoApp-7d711fe2-7a90-4b72-a820-7b62f811f344</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\ApplicationUser.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JO.DataModel\JO.DataModel.csproj" />
    <ProjectReference Include="..\JO.Persistence\JO.Persistence.csproj" />
    <ProjectReference Include="..\JO.Service\JO.Service.csproj" />
  </ItemGroup>

</Project>
