// <auto-generated />
using JO.DataModel.View;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.Roles
{
    public partial class RoleList
    {
        [Inject] private IManageUsersService ManageUsersService { get; set; } = default!;

        private List<VwJOUserAspNetRoles> roles = new();

        protected override async Task OnInitializedAsync()
        {
            roles = await ManageUsersService.GetVwJOUserAspNetRoles();
        }
    }
}
