// <auto-generated />
using JO.DataModel.Entity;
using JO.DataModel.View;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.User
{
    public partial class DivisionAccess
    {
        [Parameter] public int joUserId { get; set; }

        [Inject] private IDivisionAccessService DivisionAccessService { get; set; } = default!;
        [Inject] private IAlertService AlertService { get; set; } = default!;

        private VwJobOfferUsers user = new();
        private List<Companies> companies = new();
        private List<Divisions> divisions = new();
        private List<int> selectedDivisionIds = new();
        private int? selectedCompanyId = 1;
        private bool isSaving;

        private bool AreAllDivisionsSelected =>
            divisions.Any() && divisions.All(division => selectedDivisionIds.Contains(division.Id));

        protected override async Task OnParametersSetAsync()
        {
            user = await DivisionAccessService.GetVwJobOfferUser(joUserId);
            companies = await DivisionAccessService.GetCompanies();

            selectedDivisionIds = await DivisionAccessService.InitSelectedDivisionIds(selectedDivisionIds, joUserId);

            await OnCompanyChanged(new ChangeEventArgs
            {
                Value = selectedCompanyId
            });
        }

        private async Task OnCompanyChanged(ChangeEventArgs eventArgs)
        {
            selectedCompanyId = int.TryParse(eventArgs.Value?.ToString(), out var companyId)
                ? companyId
                : null;

            divisions.Clear();

            if (selectedCompanyId.HasValue)
                divisions = await DivisionAccessService.GetDivisions(selectedCompanyId.Value);
        }

        private void ToggleDivision(int divisionId, ChangeEventArgs eventArgs)
        {
            var isSelected = eventArgs.Value is bool value && value;

            if (isSelected)
            {
                if (!selectedDivisionIds.Contains(divisionId))
                    selectedDivisionIds.Add(divisionId);
            }
            else
            {
                selectedDivisionIds.Remove(divisionId);
            }
        }

        private void ToggleAllDivisions(ChangeEventArgs eventArgs)
        {
            var isSelected = eventArgs.Value is bool value && value;

            foreach (var division in divisions)
            {
                if (isSelected)
                {
                    if (!selectedDivisionIds.Contains(division.Id))
                        selectedDivisionIds.Add(division.Id);
                }
                else
                {
                    selectedDivisionIds.Remove(division.Id);
                }
            }
        }

        private async Task SaveDivisionAccess()
        {
            if (!selectedDivisionIds.Any())
            {
                await AlertService.Error("Please select at least one division.");
                return;
            }

            if (!await AlertService.Confirm("Save division access for this user?", "Save"))
                return;

            isSaving = true;

            try
            {
                await DivisionAccessService.UpdateUserDivisionAccess(selectedDivisionIds, joUserId);
                await AlertService.Success("Division access successfully updated.");
            }
            finally
            {
                isSaving = false;
            }
        }
    }
}
