// <auto-generated/>
using JO.DataModel.Entity;
using JO.DataModel.View;
using JO.Service.Constants;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.User
{
    public partial class EditUser
    {
        [Parameter] public int joUserId { get; set; }

        [Inject] private IManageUsersService ManageUsersService { get; set; } = default!;
        [Inject] private IAccountService AccountService { get; set; } = default!;
        [Inject] private IUtilitiesService UtilitiesService { get; set; } = default!;
        [Inject] private IAlertService AlertService { get; set; } = default!;
        [Inject] private NavigationManager Navigation { get; set; } = default!;

        private List<VwJOUserAspNetRoles> roles = new();
        private List<string> roleNames = new();
        private JobOfferUsers jobOfferUser = new();

        protected override async Task OnParametersSetAsync()
        {
            roles = await ManageUsersService.GetVwJOUserAspNetRoles();
            jobOfferUser = await ManageUsersService.GetJobOfferUser(joUserId);
            roleNames = await ManageUsersService.GetJobOfferUserRoles(jobOfferUser);
            jobOfferUser.ModifiedBy = await AccountService.GetJobOfferUserId();
        }

        private async Task SaveUser()
        {
            var errors = await CollectErrors();

            if (errors.Count > 0)
            {
                await AlertService.Errors(errors);
                return;
            }

            if (!await AlertService.Confirm("Save changes to this user?", "Save"))
                return;

            var updatedUserId = await ManageUsersService.UpdateJobOfferUser(jobOfferUser, roleNames);
            Navigation.NavigateTo($"{JORoutes.Admin.UserDetails}/{updatedUserId}");
        }

        private async Task<List<string>> CollectErrors()
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(jobOfferUser.Name))
                errors.Add("Name is required.");

            var isValidEmail = UtilitiesService.IsValidEmail(jobOfferUser.Email ?? string.Empty);

            if (!isValidEmail)
                errors.Add("Please enter a valid email address.");

            if (isValidEmail && await ManageUsersService.IsUserExists(jobOfferUser.Email!, jobOfferUser.Id))
                errors.Add("User already exists.");

            if (roleNames.Count == 0)
                errors.Add("Please select at least one role.");

            return errors;
        }

        private bool AreAllRolesSelected
        {
            get
            {
                var selectableRoleNames = GetSelectableRoleNames();
                return selectableRoleNames.Count > 0 && selectableRoleNames.All(roleNames.Contains);
            }
        }

        private bool IsRoleSelected(string? roleName)
        {
            return !string.IsNullOrWhiteSpace(roleName)
                && roleNames.Contains(roleName);
        }

        private void ToggleRole(string? roleName, ChangeEventArgs eventArgs)
        {
            if (string.IsNullOrWhiteSpace(roleName))
                return;

            var isChecked = eventArgs.Value is bool value && value;

            if (isChecked)
            {
                if (!roleNames.Contains(roleName))
                    roleNames.Add(roleName);
            }
            else
            {
                roleNames.Remove(roleName);
            }
        }

        private void ToggleAllRoles(ChangeEventArgs eventArgs)
        {
            var selectableRoleNames = GetSelectableRoleNames();
            var isChecked = eventArgs.Value is bool value && value;

            if (isChecked)
            {
                foreach (var roleName in selectableRoleNames)
                {
                    if (!roleNames.Contains(roleName))
                        roleNames.Add(roleName);
                }
            }
            else
            {
                roleNames.RemoveAll(selectableRoleNames.Contains);
            }
        }

        private void ToggleIsActive(ChangeEventArgs eventArgs)
        {
            jobOfferUser.IsActive = eventArgs.Value is bool value && value;
        }

        private List<string> GetSelectableRoleNames()
        {
            return roles
                .Where(role => role.IsActive == true && !string.IsNullOrWhiteSpace(role.RoleName))
                .Select(role => role.RoleName!)
                .Distinct()
                .ToList();
        }
    }
}
