// <auto-generated />
using JO.DataModel.View;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.User
{
    public partial class JOUsers
    {
        [Inject] private IManageUsersService ManageUsersService { get; set; } = default!;

        private List<VwJobOfferUsers> jobOfferUsers = new();

        protected override async Task OnInitializedAsync()
        {
            jobOfferUsers = await ManageUsersService.GetVwJobOfferUsers();
        }
    }
}
