// <auto-generated/>
using JO.DataModel.Entity;
using JO.DataModel.View;
using JO.Service.Constants;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.User
{
    public partial class NewUser
    {
        [Inject] private IDivisionAccessService DivisionAccessService { get; set; } = default!;
        [Inject] private IManageUsersService ManageUsersService { get; set; } = default!;
        [Inject] private IAccountService AccountService { get; set; } = default!;
        [Inject] private IUtilitiesService UtilitiesService { get; set; } = default!;
        [Inject] private IAlertService AlertService { get; set; } = default!;
        [Inject] private NavigationManager Navigation { get; set; } = default!;

        private List<VwJOUserAspNetRoles> roles = new();
        private List<string> roleNames = new();
        private JobOfferUsers newUser = new();
        private List<Companies> companies = new();
        private List<Divisions> divisions = new();
        private List<int> selectedDivisionIds = new();
        private int? selectedCompanyId = 1;
        private bool isSaving;

        private bool IsDivisionAccessRequired =>
            roleNames.Contains(JOUserRole.DivisionHeadApproverL1)
            || roleNames.Contains(JOUserRole.DivisionHeadApproverL2);

        private bool AreAllDivisionsSelected =>
            divisions.Any() && divisions.All(division => selectedDivisionIds.Contains(division.Id));

        protected override async Task OnInitializedAsync()
        {
            roles = await ManageUsersService.GetVwJOUserAspNetRoles();
            companies = await DivisionAccessService.GetCompanies();
            await OnCompanyChanged(new ChangeEventArgs { Value = selectedCompanyId });

            newUser.IsActive = true;
            newUser.CreatedBy = await AccountService.GetJobOfferUserId();
        }

        private async Task SaveUser()
        {
            if (isSaving)
                return;

            isSaving = true;

            try
            {
                var errors = await CollectErrors();

                if (errors.Count > 0)
                {
                    await AlertService.Errors(errors);
                    return;
                }

                if (!await AlertService.Confirm("Save this user?", "Save"))
                    return;

                var joUserId = await ManageUsersService.CreateJobOfferUser(newUser, roleNames);
                if (selectedDivisionIds.Any())
                    await DivisionAccessService.UpdateUserDivisionAccess(selectedDivisionIds, joUserId);

                Navigation.NavigateTo($"{JORoutes.Admin.UserDetails}/{joUserId}");
            }
            finally
            {
                isSaving = false;
            }
        }

        private async Task<List<string>> CollectErrors()
        {
            var errors = new List<string>();

            if (string.IsNullOrWhiteSpace(newUser.Name))
                errors.Add("Name is required.");

            var isValidEmail = UtilitiesService.IsValidEmail(newUser.Email ?? string.Empty);

            if (!isValidEmail)
                errors.Add("Please enter a valid email address.");

            if (isValidEmail && await ManageUsersService.IsUserExists(newUser.Email!))
                errors.Add("User already exists.");

            if (roleNames.Count == 0)
                errors.Add("Please select at least one role.");

            if (IsDivisionAccessRequired && !selectedDivisionIds.Any())
                errors.Add("Please select at least one division for the Division Head Approver L1 or Division Head Approver L2 role.");

            return errors;
        }

        private async Task OnCompanyChanged(ChangeEventArgs eventArgs)
        {
            selectedCompanyId = int.TryParse(eventArgs.Value?.ToString(), out var companyId)
                ? companyId
                : null;

            divisions.Clear();

            if (selectedCompanyId.HasValue)
                divisions = await DivisionAccessService.GetDivisions(selectedCompanyId.Value);
        }

        private void ToggleDivision(int divisionId, ChangeEventArgs eventArgs)
        {
            var isSelected = eventArgs.Value is bool value && value;

            if (isSelected)
            {
                if (!selectedDivisionIds.Contains(divisionId))
                    selectedDivisionIds.Add(divisionId);
            }
            else
            {
                selectedDivisionIds.Remove(divisionId);
            }
        }

        private void ToggleAllDivisions(ChangeEventArgs eventArgs)
        {
            var isSelected = eventArgs.Value is bool value && value;

            foreach (var division in divisions)
            {
                if (isSelected)
                {
                    if (!selectedDivisionIds.Contains(division.Id))
                        selectedDivisionIds.Add(division.Id);
                }
                else
                {
                    selectedDivisionIds.Remove(division.Id);
                }
            }
        }

        private bool AreAllRolesSelected
        {
            get
            {
                var selectableRoleNames = GetSelectableRoleNames();
                return selectableRoleNames.Count > 0 && selectableRoleNames.All(roleNames.Contains);
            }
        }

        private bool IsRoleSelected(string? roleName)
        {
            return !string.IsNullOrWhiteSpace(roleName)
                && roleNames.Contains(roleName);
        }

        private void ToggleRole(string? roleName, ChangeEventArgs eventArgs)
        {
            if (string.IsNullOrWhiteSpace(roleName))
                return;

            var isChecked = eventArgs.Value is bool value && value;

            if (isChecked)
            {
                if (!roleNames.Contains(roleName))
                    roleNames.Add(roleName);
            }
            else
            {
                roleNames.Remove(roleName);
            }
        }

        private void ToggleAllRoles(ChangeEventArgs eventArgs)
        {
            var selectableRoleNames = GetSelectableRoleNames();
            var isChecked = eventArgs.Value is bool value && value;

            if (isChecked)
            {
                foreach (var roleName in selectableRoleNames)
                {
                    if (!roleNames.Contains(roleName))
                        roleNames.Add(roleName);
                }
            }
            else
            {
                roleNames.RemoveAll(selectableRoleNames.Contains);
            }
        }

        private List<string> GetSelectableRoleNames()
        {
            return roles
                .Where(role => role.IsActive == true && !string.IsNullOrWhiteSpace(role.RoleName))
                .Select(role => role.RoleName!)
                .Distinct()
                .ToList();
        }
    }
}
