// <auto-generated/>
using JO.DataModel.View;
using JO.Service.Constants;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.User
{
    public partial class UserDetails
    {
        [Parameter] public int joUserId { get; set; }

        [Inject] private IManageUsersService ManageUsersService { get; set; } = default!;
        [Inject] private NavigationManager Navigation { get; set; } = default!;

        private List<VwJobOfferUsersAndRoles> userDetails = new();

        private List<string> RoleNames => userDetails
            .Where(user => !string.IsNullOrWhiteSpace(user.RoleName))
            .Select(user => user.RoleName!)
            .Distinct()
            .OrderBy(roleName => roleName)
            .ToList();

        protected override async Task OnParametersSetAsync()
        {
            userDetails = await ManageUsersService.GetVwJobOfferUsersAndRoles(joUserId);
        }

        private void GoBack()
        {
            Navigation.NavigateTo(JORoutes.Admin.Users);
        }
    }
}
