// <auto-generated />
using JO.DataModel.View;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.Company
{
    public partial class CompanyDetails
    {
        [Parameter] public int companyId { get; set; }

        [Inject] private ICompanyService CompanyService { get; set; } = default!;

        private VwCompanies company = new();
        private List<VwDivisions> divisions = new();

        protected override async Task OnParametersSetAsync()
        {
            company = await CompanyService.GetVwCompany(companyId);
            divisions = await CompanyService.GetVwDivisions(companyId);
        }
    }
}
