// <auto-generated />
using JO.DataModel.View;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;

namespace JO.BlazorDemoApp.Components.Pages.Admin.Company
{
    public partial class CompanyList
    {
        [Inject] private ICompanyService CompanyService { get; set; } = default!;

        private List<VwCompanies> companies = new();

        protected override async Task OnInitializedAsync()
        {
            companies = await CompanyService.GetVwCompanies();
        }
    }
}
