Create View vw_DboxCandidates
As
Select dbxc.Id,dbxc.DboxRefNum
,vwcsg.CompanyName,vwcsg.GradeName
,[EmailAddress]
,[HasDataPrivacyConsent]
,[CandidateFullName]
,[FormCompletedDate]
,[PositionAppliedFor]
,[UnilabDivision]
,[ExpectedMonthlyBasicSalary]
,[Age]
,[EmploymentStatus]
,[RelevantExperience]
,[CurrentEmployerName]
,[LastEmployerIndustry]
,[LastPositionHeld]
,[CurrentMonthlyBasicSalary]
,[GuaranteedMonthsPay]
,[AnnualGuaranteedBonusDescription]
,[AnnualGuaranteedBonusAmount]
,[MonthlyAllowanceDescription]
,[MonthlyAllowanceAmount]
,[NonMonthlyAllowanceDescription]
,[NonMonthlyAllowanceAmount]
,[MonthlyNonTaxableAllowanceDescription]
,[MonthlyNonTaxableAllowanceAmount]
,[AnnualNonTaxableAllowanceDescription]
,[AnnualNonTaxableAllowanceAmount]
,[AnnualProfitSharingAmount]
,[AnnualIncentiveDescription]
,[AnnualIncentiveAmount]
,[AnnualVariablePayDescription]
,[AnnualVariablePayAmount]
,[EmployeeHmoBenefitLimit]
,[DependentHmoBenefitLimit]
,[DentalBenefit]
,[MedicineReimbursementBenefit]
,[OpticalBenefit]
,[OtherHealthBenefits]
,[VacationLeaveBenefit]
,[SickLeaveBenefit]
,[OtherLeaveBenefits]
,[LifeInsuranceBenefit]
,[OtherBenefits]
,[VehicleBenefit]
,[MobilePhoneBenefit]
From DboxCandidates dbxc
Left Join vw_CompanySalaryGrades vwcsg On vwcsg.Id=dbxc.CSGId
Left Join CandidateResponses crs On crs.Id=dbxc.ResponseId;