<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.6.0" />
    <PackageReference Include="EPPlus" Version="8.6.0" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.25" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.25" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="PuppeteerSharp" Version="25.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JO.DataModel\JO.DataModel.csproj" />
    <ProjectReference Include="..\JO.Persistence\JO.Persistence.csproj" />
  </ItemGroup>

</Project>
