// <auto-generated />
using JO.BlazorDemoApp.Components.Pages.JobOffer;
using JO.DataModel.Entity;
using JO.DataModel.View;
using JO.Service.Constants;
using JO.Service.Services;
using JO.Service.Services.Contracts;
using Microsoft.AspNetCore.Components;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace JO.BlazorDemoApp.Components.Pages.TALead.ForNegotiation
{
    public partial class TALeadJOAnalysisForNego
    {
        [Inject] private IAlertService AlertService { get; set; } = default!;
        [Inject] private IAccountService AccountService { get; set; } = default!;
        [Inject] private ICompensationService CompensationService { get; set; } = default!;
        [Inject] private NavigationManager Navigation { get; set; } = default!;

        [Parameter] public int jobOfferId { get; set; }
        private AnalysisForNego? analysis;

        private async Task HandleGoBack()
        {
            if (!await AlertService.Confirm(
                title: "Go back without saving?",
                confirmText: "Yes"))
            {
                return;
            }

            else if (analysis.JobOffer.WorkFlowId == 1 || analysis.JobOffer.WorkFlowId == null)
            {
                Navigation.NavigateTo(JORoutes.TALead.Candidates);
            }
            else
            {
                Navigation.NavigateTo(JORoutes.TALead.JobOfferTracker);
            }
        }

        private async Task SaveAnalysis()
        {
            if (analysis is not null)
            {
                await analysis.SaveAnalysis();
            }
        }

        private async Task SubmitForApproval()
        {
            if (analysis is not null)
            {
                await analysis.TALeadSubmitForApproval(JORoutes.TALead.JobOfferDetails);
            }
        }
    }
}
