CREATE TABLE [dbo].[CandidateResponseRawData] (
    [Id]                                    INT             IDENTITY (1, 1) NOT NULL,
    [CandidateResponseId]                   NVARCHAR (MAX)  NULL,
    [ResponseStartedAt]                     NVARCHAR (MAX)  NULL,
    [ResponseCompletedAt]                   NVARCHAR (MAX)  NULL,
    [EmailAddress]                          NVARCHAR (MAX)  NULL,
    [RespondentName]                        NVARCHAR (MAX)  NULL,
    [HasDataPrivacyConsent]                 NVARCHAR (MAX)  NULL,
    [CandidateFullName]                     NVARCHAR (MAX)  NULL,
    [FormCompletedDate]                     NVARCHAR (MAX)  NULL,
    [PositionAppliedFor]                    NVARCHAR (MAX)  NULL,
    [UnilabDivision]                        NVARCHAR (MAX)  NULL,
    [ExpectedMonthlyBasicSalary]            NVARCHAR (MAX)  NULL,
    [Age]                                   NVARCHAR (MAX)  NULL,
    [EmploymentStatus]                      NVARCHAR (MAX)  NULL,
    [RelevantExperience]                    NVARCHAR (MAX)  NULL,
    [CurrentEmployerName]                   NVARCHAR (MAX)  NULL,
    [LastEmployerIndustry]                  NVARCHAR (MAX)  NULL,
    [LastPositionHeld]                      NVARCHAR (MAX)  NULL,
    [CurrentMonthlyBasicSalary]             DECIMAL (18, 2) NULL,
    [GuaranteedMonthsPay]                   NVARCHAR (MAX)  NULL,
    [AnnualGuaranteedBonusDescription]      NVARCHAR (MAX)  NULL,
    [AnnualGuaranteedBonusAmount]           NVARCHAR (MAX)  NULL,
    [MonthlyAllowanceDescription]           NVARCHAR (MAX)  NULL,
    [MonthlyAllowanceAmount]                NVARCHAR (MAX)  NULL,
    [NonMonthlyAllowanceDescription]        NVARCHAR (MAX)  NULL,
    [NonMonthlyAllowanceAmount]             NVARCHAR (MAX)  NULL,
    [MonthlyNonTaxableAllowanceDescription] NVARCHAR (MAX)  NULL,
    [MonthlyNonTaxableAllowanceAmount]      NVARCHAR (MAX)  NULL,
    [AnnualNonTaxableAllowanceDescription]  NVARCHAR (MAX)  NULL,
    [AnnualNonTaxableAllowanceAmount]       NVARCHAR (MAX)  NULL,
    [AnnualProfitSharingAmount]             NVARCHAR (MAX)  NULL,
    [AnnualIncentiveDescription]            NVARCHAR (MAX)  NULL,
    [AnnualIncentiveAmount]                 NVARCHAR (MAX)  NULL,
    [AnnualVariablePayDescription]          NVARCHAR (MAX)  NULL,
    [AnnualVariablePayAmount]               NVARCHAR (MAX)  NULL,
    [EmployeeHmoBenefitLimit]               NVARCHAR (MAX)  NULL,
    [DependentHmoBenefitLimit]              NVARCHAR (MAX)  NULL,
    [DentalBenefit]                         NVARCHAR (MAX)  NULL,
    [MedicineReimbursementBenefit]          NVARCHAR (MAX)  NULL,
    [OpticalBenefit]                        NVARCHAR (MAX)  NULL,
    [OtherHealthBenefits]                   NVARCHAR (MAX)  NULL,
    [VacationLeaveBenefit]                  NVARCHAR (MAX)  NULL,
    [SickLeaveBenefit]                      NVARCHAR (MAX)  NULL,
    [OtherLeaveBenefits]                    NVARCHAR (MAX)  NULL,
    [LifeInsuranceBenefit]                  NVARCHAR (MAX)  NULL,
    [OtherBenefits]                         NVARCHAR (MAX)  NULL,
    [VehicleBenefit]                        NVARCHAR (MAX)  NULL,
    [MobilePhoneBenefit]                    NVARCHAR (MAX)  NULL,
    [CreatedAt]                             DATETIME        NULL,
    [CreatedBy]                             INT             NULL,
    [InvalidResponse]                       BIT             NULL,
    [ErrorMessage]                          NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_CandidateResponseRawData_1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

