CREATE TABLE [dbo].[CompBenPckgs] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [PckgName]   NVARCHAR (200) NULL,
    [CompId]     INT            NULL,
    [SGId]       INT            NULL,
    [TypeId]     INT            NULL,
    [AreaId]     INT            NULL,
    [SchedId]    INT            NULL,
    [ShiftId]    INT            NULL,
    [ClassId]    INT            NULL,
    [FreqId]     INT            NULL,
    [MRIId]      INT            NULL,
    [Motorized]  BIT            NULL,
    [AllowTrans] BIT            NULL,
    [AllowSpec]  BIT            NULL,
    [Incentive]  BIT            NULL,
    [Annual]     BIT            NULL,
    [Swipe]      BIT            NULL,
    [CreatedBy]  INT            NULL,
    [CreatedAt]  DATETIME       NULL,
    [ModifiedBy] INT            NULL,
    [ModifiedAt] DATETIME       NULL,
    CONSTRAINT [PK_CompBenPckgs] PRIMARY KEY CLUSTERED ([Id] ASC)
);

